### ISSUE TITLE
Add a "real" license to projects

### ISSUE THREAD

**Issue by n8zach** [rdp/open-source-how-to-popularize-your-project#12]
One major issue I see with your projects being leveraged/adoptes/contributed-to/used by others is the missing license.

A permissive (non-toxic) license like MIT or Apache would make these much more attractive.

**Comment by rdp** [comment]
Is this a suggestion for particular projects or just in general?

On Tuesday, January 10, 2023, n8zach ***@***.***> wrote:
> One major issue I see with your projects being
leveraged/adoptes/contributed-to/used by others is the missing license.
>
> A permissive (non-toxic) license like MIT or Apache would make these much
more attractive.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.<
https://ci5.googleusercontent.com/proxy/TBnoTNBCtfPktHKu7Xxp0k6xrLu1_Kl88FKLU4FOU-nf6KkFCo_QrGCt5l7MAQXzqsvIWTGkxpp6O_rMLWacugtbCDQWIgClMPIOvofHTCtBoYTtTe62x-jHGPUN4NATjlAEAhaI_RLipVr83pmIj8-3MAgDTbF3my3vCjWjgHqCFpiNu4NXpTyBysBBwTF4MIcgmRNz3TqXfubvhObzCwfA6TV4tRF2tMY=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUCXHTJD4QRA3GSWWJ3WRXK6NA5CNFSM6AAAAAATXJV6X6WGG33NNVSW45C7OR4XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHFWFCWL4.gif>Message
ID: ***@***.***>

**Comment by n8zach** [comment]
In general.  Without any license they are considered copyrighted material and not open source and therefore cannot be adopted by others.  Attaching a permissive license such as MIT or Apache 2 would allow others to investigate and adopt them without fear.

**Comment by rdp** [comment]
attempted to add it :)
